spring:
  datasource:
    url: jdbc:mysql://172.20.88.72:3306/yundisk?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: 123456

custom:
  profiles: prod
  datasource:
    names: master,slave
    master:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://172.20.88.158:5601/im
      username: admin
      password: admin123
    slave:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://172.20.88.72:3306/yundisk?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: 123456

mybatis:
  mapperLocations: classpath:/PgsqlMapper/*.xml,classpath:/MysqlMapper/*.xml
server:
  port: 18080
  servlet:
    context-path: /dfsync_deletefiles_quartz